### ISSUE TITLE
Some ideas.

### ISSUE THREAD

**Issue by rguy98** [Thorfusion/solder.py#26]
1) Ultimate Tier factory machines.

2) Factory versions of other machines with item-based inputs (e.g. Sawmill, Chemical Oxidizer, PRC)

3) Fluid version of the Digital Miner

4) Cable covers, similar to AE2's facades

5) Multiblock gas tank, similar to the Dynamic tank.

**Comment by maggi373** [comment]
wrong repo mate, please go to https://github.com/Thorfusion/Mekanism-Community-Edition/issues to submit your issue
